In [1]:
using SparseArrays
using Printf

In [2]:
A = spdiagm(0 => 1*ones(4), 1=>2*ones(3), -1=>3*ones(3))

4×4 SparseMatrixCSC{Float64, Int64} with 10 stored entries:
 1.0  2.0   ⋅    ⋅ 
 3.0  1.0  2.0   ⋅ 
  ⋅   3.0  1.0  2.0
  ⋅    ⋅   3.0  1.0

In [3]:
show(A)

sparse([1, 2, 1, 2, 3, 2, 3, 4, 3, 4], [1, 1, 2, 2, 2, 3, 3, 3, 4, 4], [1.0, 3.0, 2.0, 1.0, 3.0, 2.0, 1.0, 3.0, 2.0, 1.0], 4, 4)

In [4]:
A.m # no. of rows

4

In [5]:
A.n # no. of cols

4

In [6]:
A.colptr

5-element Vector{Int64}:
  1
  3
  6
  9
 11

In [7]:
A.nzval

10-element Vector{Float64}:
 1.0
 3.0
 2.0
 1.0
 3.0
 2.0
 1.0
 3.0
 2.0
 1.0

In [8]:
A.rowval

10-element Vector{Int64}:
 1
 2
 1
 2
 3
 2
 3
 4
 3
 4

In [9]:
for j in 1:A.n # loop over columns
    for k in A.colptr[j]:A.colptr[j+1]-1 # looping over the nonzero entries in column j
        @printf("A[%d,%d] = %g\n", A.rowval[k], j, A.nzval[k])
    end
end

A[1,1] = 1
A[2,1] = 3
A[1,2] = 2
A[2,2] = 1
A[3,2] = 3
A[2,3] = 2
A[3,3] = 1
A[4,3] = 3
A[3,4] = 2
A[4,4] = 1
